// <auto-generated />
namespace DoAnChuyenNganh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Update_BinhLuan_AddUserId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_BinhLuan_AddUserId));
        
        string IMigrationMetadata.Id
        {
            get { return "202510130949383_Update_BinhLuan_AddUserId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
