// <auto-generated />
namespace DoAnChuyenNganh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Add_BienTheId_To_AnhSanPham : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_BienTheId_To_AnhSanPham));
        
        string IMigrationMetadata.Id
        {
            get { return "202510051644075_Add_BienTheId_To_AnhSanPham"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
